allow moving directories
npm/move-file pull request #2
Opened 2020-11-18 17:18 UTC by nlf

sometimes we want to `rename()` a directory too, this change allows that to also work

## References

2020-11-18 18:59 UTC, isaacs requested changes
One performance nit, and a question about how we handle symlinks.  (Symlinks shouldn't be relevant for npm/cli, since they're not allowed within packages, but as this is a general purpose module, it'd be worth having an answer there.)

2020-11-18 18:59 UTC, isaacs commented on index.js
> +        for (const file of files) {
This could be more efficient by parallelizing.

```js
await Promise.all(files.map(file => moveFile(join(source, file), join(destination, file), options)))
```

2020-11-18 18:59 UTC, isaacs commented on index.js
> +      } else {
Hmm, what happens if it's a symlink to a directory?  It looks like that'll fail with `EISDIR`, if I'm reading this right?

2020-11-18 18:59 UTC, isaacs commented on index.js
> +      } else {
If we want to mimic `cp -LR` behavior, we can replace the `lstat` with `stat`.  If we want to mimic `cp -R`, we should skip symlinks entirely.  If we want to mimic `rename(1)` (which is kind of the stated intent of this module), then we should read the link and create a destination symlink the same value.

2020-11-18 19:01 UTC, nlf commented on index.js
> +        for (const file of files) {
sure, we can parallelize :+1:

2020-11-18 19:11 UTC, nlf commented on index.js
> +      } else {
yeah i was trying to decide what to do about symlinks.. i think we should mimic `rename(1)` as much as possible, so i'll add a clause such that symlinks are created in the destination with the same target as the source

2020-11-20 18:06 UTC, nlf commented on index.js
> +      } else {
symlinks are now batched until the end, as is removing of the source files to give a little better support for detecting the type of thing we're linking to since windows cares about these things.

so now we:
recursively create all the plain files in the destination
create all the symlinks in the destination by using `stat` calls against the original directory to determine type(s) of symlinks
rimraf the original directory entirely

2020-11-28 01:46 UTC, isaacs approved these changes
LGTM!

2021-01-14 17:05 UTC, closed without merging